In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
train['source'] = 'train'
test['source']='test'

In [4]:
data = pd.concat([train,test],ignore_index=True)
data.reset_index(drop=True)

,Item_Fat_Content,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Location_Type,Outlet_Size,Outlet_Type,source
0,Low Fat,FDA15,249.8092,3735.1380,Dairy,0.016047,9.300,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
1,Regular,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.920,2009,OUT018,Tier 3,Medium,Supermarket Type2,train
2,Low Fat,FDN15,141.6180,2097.2700,Meat,0.016760,17.500,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
3,Regular,FDX07,182.0950,732.3800,Fruits and Vegetables,0.000000,19.200,1998,OUT010,Tier 3,NaN,Grocery Store,train
4,Low Fat,NCD19,53.8614,994.7052,Household,0.000000,8.930,1987,OUT013,Tier 3,High,Supermarket Type1,train
5,Regular,FDP36,51.4008,556.6088,Baking Goods,0.000000,10.395,2009,OUT018,Tier 3,Medium,Supermarket Type2,train
6,Regular,FDO10,57.6588,343.5528,Snack Foods,0.012741,13.650,1987,OUT013,Tier 3,High,Supermarket Type1,train
7,Low Fat,FDP10,107.7622,4022.7636,Snack Foods,0.127470,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,train
8,Regular,FDH17,96.9726,1076.5986,Frozen Foods,0.016687,16.200,2002,OUT045,Tier 2,NaN,Supermarket Type1,train
9,Regular,FDU28,187.8214,4710.5350,Frozen Foods,0.094450,19.200,2007,OUT017,Tier 2,NaN,Supermarket Type1,train
10,Low Fat,FDY07,45.5402,1516.0266,Fruits and Vegetables,0.000000,11.800,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
11,Regular,FDA03,144.1102,2187.1530,Dairy,0.045464,18.500,1997,OUT046,Tier 1,Small,Supermarket Type1,train
12,Regular,FDX32,145.4786,1589.2646,Fruits and Vegetables,0.100014,15.100,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
13,Regular,FDS46,119.6782,2145.2076,Snack Foods,0.047257,17.600,1997,OUT046,Tier 1,Small,Supermarket Type1,train
14,Low Fat,FDF32,196.4426,1977.4260,Fruits and Vegetables,0.068024,16.350,1987,OUT013,Tier 3,High,Supermarket Type1,train
15,Regular,FDP49,56.3614,1547.3192,Breakfast,0.069089,9.000,1997,OUT046,Tier 1,Small,Supermarket Type1,train
16,Low Fat,NCB42,115.3492,1621.8888,Health and Hygiene,0.008596,11.800,2009,OUT018,Tier 3,Medium,Supermarket Type2,train
17,Regular,FDP49,54.3614,718.3982,Breakfast,0.069196,9.000,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
18,Low Fat,DRI11,113.2834,2303.6680,Hard Drinks,0.034238,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,train
19,Low Fat,FDU02,230.5352,2748.4224,Dairy,0.102492,13.350,2004,OUT035,Tier 2,Small,Supermarket Type1,train
20,Regular,FDN22,250.8724,3775.0860,Snack Foods,0.138190,18.850,1987,OUT013,Tier 3,High,Supermarket Type1,train
21,Regular,FDW12,144.5444,4064.0432,Baking Goods,0.035400,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,train
22,Low Fat,NCB30,196.5084,1587.2672,Household,0.025698,14.600,2004,OUT035,Tier 2,Small,Supermarket Type1,train
23,Low Fat,FDC37,107.6938,214.3876,Baking Goods,0.057557,NaN,1985,OUT019,Tier 1,Small,Grocery Store,train
24,Regular,FDR28,165.0210,4078.0250,Frozen Foods,0.025896,13.850,1997,OUT046,Tier 1,Small,Supermarket Type1,train
25,Low Fat,NCD06,45.9060,838.9080,Household,0.099887,13.000,2007,OUT017,Tier 2,NaN,Supermarket Type1,train
26,Regular,FDV10,42.3112,1065.2800,Snack Foods,0.066693,7.645,2004,OUT035,Tier 2,Small,Supermarket Type1,train
27,low fat,DRJ59,39.1164,308.9312,Hard Drinks,0.019356,11.650,1987,OUT013,Tier 3,High,Supermarket Type1,train
28,Regular,FDE51,45.5086,178.4344,Dairy,0.161467,5.925,1998,OUT010,Tier 3,NaN,Grocery Store,train
29,Regular,FDC14,43.6454,125.8362,Canned,0.072222,NaN,1985,OUT019,Tier 1,Small,Grocery Store,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14174,Regular,FDD23,186.1898,NaN,Starchy Foods,0.048645,9.500,1987,OUT013,Tier 3,High,Supermarket Type1,test
14175,Low Fat,FDP32,126.7678,NaN,Fruits and Vegetables,0.087847,6.650,2002,OUT045,Tier 2,NaN,Supermarket Type1,test
14176,Regular,FDO31,80.2960,NaN,Fruits and Vegetables,0.028977,6.760,2004,OUT035,Tier 2,Small,Supermarket Type1,test
14177,Low Fat,FDQ57,144.5760,NaN,Snack Foods,0.000000,7.275,1987,OUT013,Tier 3,High,Supermarket Type1,test
14178,Regular,FDX32,143.6786,NaN,Fruits and Vegetables,0.099375,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,test
14179,Low Fat,FDC39,207.8296,NaN,Dairy,0.158425,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,test
14180,Low Fat,FDU55,261.3278,NaN,Fruits and Vegetables,0.035911,16.200,1997,OUT046,Tier 1,Small,Supermarket Type1,test
14181,Low Fat,FDL45,123.4704,NaN,Snack Foods,0.037656,15.600,1987,OUT013,Tier 3,High,Supermarket Type1,test
14182,Low Fat,DRK37,188.8530,NaN,Soft Drinks,0.044073,5.000,1999,OUT049,Tier 1,Medium,Supermarket Type1,test
14183,Low Fat,FDK22,215.3850,NaN,Snack Foods,0.026065,9.800,1987,OUT013,Tier 3,High,Supermarket Type1,test
14184,Low Fat,DRG37,155.7972,NaN,Soft Drinks,0.000000,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,test
14185,Low Fat,FDK22,214.3850,NaN,Snack Foods,0.026234,9.800,2007,OUT017,Tier 2,NaN,Supermarket Type1,test
14186,Low Fat,DRH36,72.8696,NaN,Soft Drinks,0.033516,16.200,2009,OUT018,Tier 3,Medium,Supermarket Type2,test
14187,Regular,DRC36,173.4054,NaN,Soft Drinks,0.045168,13.000,2009,OUT018,Tier 3,Medium,Supermarket Type2,test
14188,Low Fat,DRE03,46.0718,NaN,Dairy,0.024110,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,test
14189,Regular,FDF34,196.9084,NaN,Snack Foods,0.014019,9.300,1997,OUT046,Tier 1,Small,Supermarket Type1,test
14190,Low Fat,FDZ22,82.1250,NaN,Snack Foods,0.045270,9.395,1997,OUT046,Tier 1,Small,Supermarket Type1,test
14191,Low Fat,FDC44,115.1518,NaN,Fruits and Vegetables,0.288892,15.600,1998,OUT010,Tier 3,NaN,Grocery Store,test
14192,Low Fat,FDN31,188.0530,NaN,Fruits and Vegetables,0.072529,NaN,1985,OUT027,Tier 3,Medium,Supermarket Type3,test
14193,Regular,FDO03,229.4352,NaN,Meat,0.037092,10.395,2007,OUT017,Tier 2,NaN,Supermarket Type1,test
14194,reg,FDA01,59.5904,NaN,Canned,0.054463,15.000,1999,OUT049,Tier 1,Medium,Supermarket Type1,test
14195,Low Fat,NCH42,231.1010,NaN,Household,0.036594,6.860,1999,OUT049,Tier 1,Medium,Supermarket Type1,test
14196,Low Fat,FDF46,116.0834,NaN,Snack Foods,0.094053,7.070,2009,OUT018,Tier 3,Medium,Supermarket Type2,test
14197,Low Fat,DRL35,43.2770,NaN,Hard Drinks,0.030704,15.700,1997,OUT046,Tier 1,Small,Supermarket Type1,test
14198,Regular,FDW46,63.4484,NaN,Snack Foods,0.070411,13.000,1999,OUT049,Tier 1,Medium,Supermarket Type1,test
14199,Regular,FDB58,141.3154,NaN,Snack Foods,0.013496,10.500,1997,OUT046,Tier 1,Small,Supermarket Type1,test
14200,Regular,FDD47,169.1448,NaN,Starchy Foods,0.142991,7.600,2009,OUT018,Tier 3,Medium,Supermarket Type2,test
14201,Low Fat,NCO17,118.7440,NaN,Health and Hygiene,0.073529,10.000,2002,OUT045,Tier 2,NaN,Supermarket Type1,test
14202,Regular,FDJ26,214.6218,NaN,Canned,0.000000,15.300,2007,OUT017,Tier 2,NaN,Supermarket Type1,test
14203,Regular,FDU37,79.7960,NaN,Canned,0.104720,9.500,2002,OUT045,Tier 2,NaN,Supermarket Type1,test

In [5]:
print(data.shape,train.shape,test.shape)

(14204, 13) (8523, 13) (5681, 12)

# Data Exploration

In [6]:
data.apply(lambda x: sum(x.isnull()))

Item_Fat_Content                0
Item_Identifier                 0
Item_MRP                        0
Item_Outlet_Sales            5681
Item_Type                       0
Item_Visibility                 0
Item_Weight                  2439
Outlet_Establishment_Year       0
Outlet_Identifier               0
Outlet_Location_Type            0
Outlet_Size                  4016
Outlet_Type                     0
source                          0
dtype: int64

In [7]:
data.describe()

,Item_MRP,Item_Outlet_Sales,Item_Visibility,Item_Weight,Outlet_Establishment_Year
count,14204.000000,8523.000000,14204.000000,11765.000000,14204.000000
mean,141.004977,2181.288914,0.065953,12.792854,1997.830681
std,62.086938,1706.499616,0.051459,4.652502,8.371664
min,31.290000,33.290000,0.000000,4.555000,1985.000000
25%,94.012000,834.247400,0.027036,8.710000,1987.000000
50%,142.247000,1794.331000,0.054021,12.600000,1999.000000
75%,185.855600,3101.296400,0.094037,16.750000,2004.000000
max,266.888400,13086.964800,0.328391,21.350000,2009.000000

In [8]:
data.apply(lambda x: len(x.unique()))

Item_Fat_Content                 5
Item_Identifier               1559
Item_MRP                      8052
Item_Outlet_Sales             3494
Item_Type                       16
Item_Visibility              13006
Item_Weight                    416
Outlet_Establishment_Year        9
Outlet_Identifier               10
Outlet_Location_Type             3
Outlet_Size                      4
Outlet_Type                      4
source                           2
dtype: int64

In [9]:
categorical_columns = [x for x in data.dtypes.index if data.dtypes[x]=='object']
categorical_columns = [x for x in categorical_columns if x not in ['Outlet_Identifier',
                                                                  'source']]
for col in categorical_columns:
    print('\nFrequency of categories for variable %s'%col)
    print(data[col].value_counts())

Frequency of categories for variable Item_Fat_Content
Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: Item_Fat_Content, dtype: int64

Frequency of categories for variable Item_Identifier
FDT12    10
FDQ49    10
DRM11    10
NCV29    10
FDE34    10
FDV23    10
FDE24    10
FDL52    10
FDH40    10
FDR19    10
FDY02    10
FDP27    10
NCH30    10
FDS03    10
FDT36    10
FDH41    10
FDJ26    10
NCH18    10
FDX08    10
FDH28    10
FDC47    10
FDS13    10
NCO55    10
FDV10    10
FDX03    10
FDK33    10
NCC31    10
FDY08    10
FDH14    10
FDZ45    10
         ..
FDG14     8
FDW57     8
FDJ04     8
FDS60     8
FDL28     8
FDM16     8
FDJ27     8
FDL08     8
FDA57     8
FDY57     8
FDK22     8
FDA48     8
NCC19     8
FDI10     8
FDW31     8
FDF45     8
NCK42     8
FDX49     7
FDS22     7
FDO33     7
FDR51     7
NCW54     7
FDM50     7
FDH58     7
FDI46     7
NCL42     7
FDM10     7
FDL50     7
FDM52     7
DRN11     7
Name: Item_Identifier, Length: 1559, dtype: int64

Frequency of categories for variable Item_Type
Fruits and Vegetables    2013
Snack Foods              1989
Household                1548
Frozen Foods             1426
Dairy                    1136
Baking Goods             1086
Canned                   1084
Health and Hygiene        858
Meat                      736
Soft Drinks               726
Breads                    416
Hard Drinks               362
Others                    280
Starchy Foods             269
Breakfast                 186
Seafood                    89
Name: Item_Type, dtype: int64

Frequency of categories for variable Outlet_Location_Type
Tier 3    5583
Tier 2    4641
Tier 1    3980
Name: Outlet_Location_Type, dtype: int64

Frequency of categories for variable Outlet_Size
Medium    4655
Small     3980
High      1553
Name: Outlet_Size, dtype: int64

Frequency of categories for variable Outlet_Type
Supermarket Type1    9294
Grocery Store        1805
Supermarket Type3    1559
Supermarket Type2    1546
Name: Outlet_Type, dtype: int64

# Data Cleaning

In [10]:
data.head(5)

,Item_Fat_Content,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Location_Type,Outlet_Size,Outlet_Type,source
0,Low Fat,FDA15,249.8092,3735.1380,Dairy,0.016047,9.30,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
1,Regular,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.92,2009,OUT018,Tier 3,Medium,Supermarket Type2,train
2,Low Fat,FDN15,141.6180,2097.2700,Meat,0.016760,17.50,1999,OUT049,Tier 1,Medium,Supermarket Type1,train
3,Regular,FDX07,182.0950,732.3800,Fruits and Vegetables,0.000000,19.20,1998,OUT010,Tier 3,NaN,Grocery Store,train
4,Low Fat,NCD19,53.8614,994.7052,Household,0.000000,8.93,1987,OUT013,Tier 3,High,Supermarket Type1,train

In [11]:
item_avg_weight = data.groupby('Item_Identifier').Item_Weight.mean()

In [12]:
miss_bool = data['Item_Weight'].isnull()

In [13]:
#Impute data and check #missing values before and after imputation to confirm
print ('Orignal #missing: %d'% sum(miss_bool))
data.loc[miss_bool,'Item_Weight'] = data.loc[miss_bool,'Item_Identifier'].apply(lambda x: item_avg_weight[x])
print ('Final #missing: %d'% sum(data['Item_Weight'].isnull()))

Orignal #missing: 2439
Final #missing: 0

In [14]:
#Outlet_Size
from scipy.stats import mode

In [15]:
#Determing the mode for each
outlet_size_mode = data.pivot_table(values='Outlet_Size', columns='Outlet_Type',aggfunc=(lambda x: x.mode())) 
print('Mode for each Outlet_Type: ')
print(outlet_size_mode)

#Get a boolean variable specifying missing Item_Weight values
miss_bool = data['Outlet_Size'].isnull() 

#Impute data and check #missing values before and after imputation to confirm
print('\nOrignal #missing: %d'% sum(miss_bool))
data.loc[miss_bool,'Outlet_Size'] = data.loc[miss_bool,'Outlet_Type'].apply(lambda x: outlet_size_mode[x])
print('Final #missing: %d'%sum(data['Outlet_Size'].isnull()))

Mode for each Outlet_Type:
Outlet_Type Grocery Store Supermarket Type1 Supermarket Type2  \
Outlet_Size         Small             Small            Medium

Outlet_Type Supermarket Type3
Outlet_Size            Medium

Orignal #missing: 4016
Final #missing: 0

# Feature Engineering
1. missing values: resolved
2. combining outlet type
3. item visibility zero for some items
4. Create a broad category of Type of Item
5. Determine the years of operation of a store
4. multiple labels with same meaning in item fat content
5. Label and One Hot encoding
6. Exporting data

# Consider combining Outlet_Type

 During exploration, we decided to consider combining the Supermarket Type2 and Type3 variables. But is that a good idea? A quick way to check that could be to analyze the mean sales by type of store. If they have similar sales, then keeping them separate won’t help much.

In [16]:
data.pivot_table('Item_Outlet_Sales','Outlet_Type')

                   Item_Outlet_Sales
Outlet_Type
Grocery Store             339.828500
Supermarket Type1        2316.181148
Supermarket Type2        1995.498739
Supermarket Type3        3694.038558

In [17]:
# This shows significant difference between them and we’ll leave them as it is.

# Modify Item_Visibility

In [18]:
visibility_avg = data.pivot_table(values='Item_Visibility', index='Item_Identifier')

In [19]:
miss_bool = (data['Item_Visibility'] == 0)

In [20]:
print('Number of 0 values initially: %d'%sum(miss_bool))

Number of 0 values initially: 879

In [21]:
data.loc[miss_bool,'Item_Visibility'] = data.loc[miss_bool,'Item_Identifier'].apply(lambda x: visibility_avg.loc[x])

In [22]:
print('Numbers of 0 values after modification :%d'%sum(data['Item_Visibility']==0))

Numbers of 0 values after modification :0

In [23]:
data['Item_Visibility'].min()

0.003574698


But along with comparing products on absolute terms, 
we should look at the visibility of the product in that 
particular store as compared to the mean visibility of 
that product across all stores. This will give some idea 
about how much importance was given to that product in a 
store as compared to other stores. We can use the 
‘visibility_avg’ variable made above to achieve this.

In [24]:
#Determine another variable with means ratio
data['Item_Visibility_MeanRatio'] = data.apply(lambda x: x['Item_Visibility']/visibility_avg.loc[x['Item_Identifier']], axis=1)
print(data['Item_Visibility_MeanRatio'].describe())

count    14204.000000
mean         1.061884
std          0.235907
min          0.844563
25%          0.925131
50%          0.999070
75%          1.042007
max          3.010094
Name: Item_Visibility_MeanRatio, dtype: float64

# Create a broad category of Type of Item

In [25]:
#Get the first two characters of ID:
data['Item_Type_Combined'] = data['Item_Identifier'].apply(lambda x: x[0:2])
#Rename them to more intuitive categories:
data['Item_Type_Combined'] = data['Item_Type_Combined'].rename({'FD':'Food',
                                                             'NC':'Non-Consumable',
                                                             'DR':'Drinks'})
data['Item_Type_Combined'].value_counts()

FD    10201
NC     2686
DR     1317
Name: Item_Type_Combined, dtype: int64

 # Modify categories of Item_Fat_Content

In [26]:
#Change categories of low fat:

print('Original categories:')
print(data['Item_Fat_Content'].value_counts())

print('\nModified categories:')
data['Item_Fat_Content'] = data['Item_Fat_Content'].replace({'LF':'Low Fat',
                                                            'low fat': 'Low Fat',
                                                            'reg':'Regular'})
print(data['Item_Fat_Content'].value_counts())

Original categories:
Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: Item_Fat_Content, dtype: int64

Modified categories:
Low Fat    9185
Regular    5019
Name: Item_Fat_Content, dtype: int64

we saw there were some non-consumables as well and a fat-content should not be specified for them. So we can also create a separate category for such kind of observations.

In [27]:
#Mark non-consumables as separate category in low_fat:

data.loc[data['Item_Type_Combined'] == "NC",'Item_Fat_Content'] = "Non-Edible"
data['Item_Fat_Content'].value_counts()

Low Fat       6499
Regular       5019
Non-Edible    2686
Name: Item_Fat_Content, dtype: int64

# Determine the years of operation of a store

In [28]:
data['Outlet_Years'] = 2013 - data['Outlet_Establishment_Year']
data['Outlet_Years'].describe()

count    14204.000000
mean        15.169319
std          8.371664
min          4.000000
25%          9.000000
50%         14.000000
75%         26.000000
max         28.000000
Name: Outlet_Years, dtype: float64

# Numerical and One-Hot Coding of Categorical variables

In [29]:
#Import library:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#New variable for outlet
data['Outlet'] = le.fit_transform(data['Outlet_Identifier'])
var_mod = ['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Item_Type_Combined','Outlet_Type','Outlet']
le = LabelEncoder()
for i in var_mod:
    data[i] = le.fit_transform(data[i])

In [30]:
data

,Item_Fat_Content,Item_Identifier,Item_MRP,Item_Outlet_Sales,Item_Type,Item_Visibility,Item_Weight,Outlet_Establishment_Year,Outlet_Identifier,Outlet_Location_Type,Outlet_Size,Outlet_Type,source,Item_Visibility_MeanRatio,Item_Type_Combined,Outlet_Years,Outlet
0,0,FDA15,249.8092,3735.1380,Dairy,0.016047,9.300,1999,OUT049,0,1,1,train,0.931078,1,14,9
1,2,DRC01,48.2692,443.4228,Soft Drinks,0.019278,5.920,2009,OUT018,2,1,2,train,0.933420,0,4,3
2,0,FDN15,141.6180,2097.2700,Meat,0.016760,17.500,1999,OUT049,0,1,1,train,0.960069,1,14,9
3,2,FDX07,182.0950,732.3800,Fruits and Vegetables,0.017834,19.200,1998,OUT010,2,2,0,train,1.000000,1,15,0
4,1,NCD19,53.8614,994.7052,Household,0.009780,8.930,1987,OUT013,2,0,1,train,1.000000,2,26,1
5,2,FDP36,51.4008,556.6088,Baking Goods,0.057059,10.395,2009,OUT018,2,1,2,train,1.000000,1,4,3
6,2,FDO10,57.6588,343.5528,Snack Foods,0.012741,13.650,1987,OUT013,2,0,1,train,1.497197,1,26,1
7,0,FDP10,107.7622,4022.7636,Snack Foods,0.127470,19.000,1985,OUT027,2,1,3,train,0.870493,1,28,5
8,2,FDH17,96.9726,1076.5986,Frozen Foods,0.016687,16.200,2002,OUT045,1,2,1,train,0.924160,1,11,7
9,2,FDU28,187.8214,4710.5350,Frozen Foods,0.094450,19.200,2007,OUT017,1,2,1,train,0.963983,1,6,2
10,0,FDY07,45.5402,1516.0266,Fruits and Vegetables,0.040627,11.800,1999,OUT049,0,1,1,train,1.000000,1,14,9
11,2,FDA03,144.1102,2187.1530,Dairy,0.045464,18.500,1997,OUT046,0,2,1,train,1.036695,1,16,8
12,2,FDX32,145.4786,1589.2646,Fruits and Vegetables,0.100014,15.100,1999,OUT049,0,1,1,train,1.026360,1,14,9
13,2,FDS46,119.6782,2145.2076,Snack Foods,0.047257,17.600,1997,OUT046,0,2,1,train,0.922290,1,16,8
14,0,FDF32,196.4426,1977.4260,Fruits and Vegetables,0.068024,16.350,1987,OUT013,2,0,1,train,1.171331,1,26,1
15,2,FDP49,56.3614,1547.3192,Breakfast,0.069089,9.000,1997,OUT046,0,2,1,train,1.028073,1,16,8
16,1,NCB42,115.3492,1621.8888,Health and Hygiene,0.008596,11.800,2009,OUT018,2,1,2,train,1.003140,2,4,3
17,2,FDP49,54.3614,718.3982,Breakfast,0.069196,9.000,1999,OUT049,0,1,1,train,1.029671,1,14,9
18,0,DRI11,113.2834,2303.6680,Hard Drinks,0.034238,8.260,1985,OUT027,2,1,3,train,0.870493,0,28,5
19,0,FDU02,230.5352,2748.4224,Dairy,0.102492,13.350,2004,OUT035,1,2,1,train,0.922116,1,9,6
20,2,FDN22,250.8724,3775.0860,Snack Foods,0.138190,18.850,1987,OUT013,2,0,1,train,1.139904,1,26,1
21,2,FDW12,144.5444,4064.0432,Baking Goods,0.035400,8.315,1985,OUT027,2,1,3,train,0.954309,1,28,5
22,1,NCB30,196.5084,1587.2672,Household,0.025698,14.600,2004,OUT035,1,2,1,train,0.862894,2,9,6
23,0,FDC37,107.6938,214.3876,Baking Goods,0.057557,15.500,1985,OUT019,0,2,0,train,1.531537,1,28,4
24,2,FDR28,165.0210,4078.0250,Frozen Foods,0.025896,13.850,1997,OUT046,0,2,1,train,0.929633,1,16,8
25,1,NCD06,45.9060,838.9080,Household,0.099887,13.000,2007,OUT017,1,2,1,train,0.927507,2,6,2
26,2,FDV10,42.3112,1065.2800,Snack Foods,0.066693,7.645,2004,OUT035,1,2,1,train,1.060235,1,9,6
27,0,DRJ59,39.1164,308.9312,Hard Drinks,0.019356,11.650,1987,OUT013,2,0,1,train,1.035278,0,26,1
28,2,FDE51,45.5086,178.4344,Dairy,0.161467,5.925,1998,OUT010,2,2,0,train,1.444581,1,15,0
29,2,FDC14,43.6454,125.8362,Canned,0.072222,14.500,1985,OUT019,0,2,0,train,1.679003,1,28,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14174,2,FDD23,186.1898,NaN,Starchy Foods,0.048645,9.500,1987,OUT013,2,0,1,test,0.998238,1,26,1
14175,0,FDP32,126.7678,NaN,Fruits and Vegetables,0.087847,6.650,2002,OUT045,1,2,1,test,1.038721,1,11,7
14176,2,FDO31,80.2960,NaN,Fruits and Vegetables,0.028977,6.760,2004,OUT035,1,2,1,test,0.874563,1,9,6
14177,0,FDQ57,144.5760,NaN,Snack Foods,0.024077,7.275,1987,OUT013,2,0,1,test,1.000000,1,26,1
14178,2,FDX32,143.6786,NaN,Fruits and Vegetables,0.099375,15.100,1985,OUT027,2,1,3,test,1.019804,1,28,5
14179,0,FDC39,207.8296,NaN,Dairy,0.158425,7.405,1985,OUT027,2,1,3,test,1.326824,1,28,5
14180,0,FDU55,261.3278,NaN,Fruits and Vegetables,0.035911,16.200,1997,OUT046,0,2,1,test,0.999070,1,16,8
14181,0,FDL45,123.4704,NaN,Snack Foods,0.037656,15.600,1987,OUT013,2,0,1,test,0.874001,1,26,1
14182,0,DRK37,188.8530,NaN,Soft Drinks,0.044073,5.000,1999,OUT049,0,1,1,test,1.291142,0,14,9
14183,0,FDK22,215.3850,NaN,Snack Foods,0.026065,9.800,1987,OUT013,2,0,1,test,0.920760,1,26,1
14184,0,DRG37,155.7972,NaN,Soft Drinks,0.020225,16.200,1985,OUT027,2,1,3,test,1.000000,0,28,5
14185,0,FDK22,214.3850,NaN,Snack Foods,0.026234,9.800,2007,OUT017,1,2,1,test,0.926739,1,6,2
14186,0,DRH36,72.8696,NaN,Soft Drinks,0.033516,16.200,2009,OUT018,2,1,2,test,1.031682,0,4,3
14187,2,DRC36,173.4054,NaN,Soft Drinks,0.045168,13.000,2009,OUT018,2,1,2,test,0.962406,0,4,3
14188,0,DRE03,46.0718,NaN,Dairy,0.024110,19.600,1985,OUT027,2,1,3,test,0.925131,0,28,5
14189,2,FDF34,196.9084,NaN,Snack Foods,0.014019,9.300,1997,OUT046,0,2,1,test,0.929633,1,16,8
14190,0,FDZ22,82.1250,NaN,Snack Foods,0.045270,9.395,1997,OUT046,0,2,1,test,0.922290,1,16,8
14191,0,FDC44,115.1518,NaN,Fruits and Vegetables,0.288892,15.600,1998,OUT010,2,2,0,test,1.735564,1,15,0
14192,0,FDN31,188.0530,NaN,Fruits and Vegetables,0.072529,11.500,1985,OUT027,2,1,3,test,0.925131,1,28,5
14193,2,FDO03,229.4352,NaN,Meat,0.037092,10.395,2007,OUT017,1,2,1,test,1.033309,1,6,2
14194,2,FDA01,59.5904,NaN,Canned,0.054463,15.000,1999,OUT049,0,1,1,test,0.931078,1,14,9
14195,1,NCH42,231.1010,NaN,Household,0.036594,6.860,1999,OUT049,0,1,1,test,0.876089,2,14,9
14196,0,FDF46,116.0834,NaN,Snack Foods,0.094053,7.070,2009,OUT018,2,1,2,test,1.031964,1,4,3
14197,0,DRL35,43.2770,NaN,Hard Drinks,0.030704,15.700,1997,OUT046,0,2,1,test,1.285095,0,16,8
14198,2,FDW46,63.4484,NaN,Snack Foods,0.070411,13.000,1999,OUT049,0,1,1,test,0.923724,1,14,9
14199,2,FDB58,141.3154,NaN,Snack Foods,0.013496,10.500,1997,OUT046,0,2,1,test,0.874729,1,16,8
14200,2,FDD47,169.1448,NaN,Starchy Foods,0.142991,7.600,2009,OUT018,2,1,2,test,0.878292,1,4,3
14201,1,NCO17,118.7440,NaN,Health and Hygiene,0.073529,10.000,2002,OUT045,1,2,1,test,1.162245,2,11,7
14202,2,FDJ26,214.6218,NaN,Canned,0.088380,15.300,2007,OUT017,1,2,1,test,1.000000,1,6,2
14203,2,FDU37,79.7960,NaN,Canned,0.104720,9.500,2002,OUT045,1,2,1,test,1.029678,1,11,7

In [31]:
#One Hot Coding:
data = pd.get_dummies(data, columns=['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Outlet_Type',
                              'Item_Type_Combined','Outlet'])

In [32]:
data.dtypes

Item_Identifier               object
Item_MRP                     float64
Item_Outlet_Sales            float64
Item_Type                     object
Item_Visibility              float64
Item_Weight                  float64
Outlet_Establishment_Year      int64
Outlet_Identifier             object
source                        object
Item_Visibility_MeanRatio    float64
Outlet_Years                   int64
Item_Fat_Content_0             uint8
Item_Fat_Content_1             uint8
Item_Fat_Content_2             uint8
Outlet_Location_Type_0         uint8
Outlet_Location_Type_1         uint8
Outlet_Location_Type_2         uint8
Outlet_Size_0                  uint8
Outlet_Size_1                  uint8
Outlet_Size_2                  uint8
Outlet_Type_0                  uint8
Outlet_Type_1                  uint8
Outlet_Type_2                  uint8
Outlet_Type_3                  uint8
Item_Type_Combined_0           uint8
Item_Type_Combined_1           uint8
Item_Type_Combined_2           uint8
Outlet_0                       uint8
Outlet_1                       uint8
Outlet_2                       uint8
Outlet_3                       uint8
Outlet_4                       uint8
Outlet_5                       uint8
Outlet_6                       uint8
Outlet_7                       uint8
Outlet_8                       uint8
Outlet_9                       uint8
dtype: object

In [33]:
# Lets look at the 3 columns formed from Item_Fat_Content.

data[['Item_Fat_Content_0','Item_Fat_Content_1','Item_Fat_Content_2']].head()

   Item_Fat_Content_0  Item_Fat_Content_1  Item_Fat_Content_2
0                   1                   0                   0
1                   0                   0                   1
2                   1                   0                   0
3                   0                   0                   1
4                   0                   1                   0

# Exporting Data

In [34]:
#Drop the columns which have been converted to different types:
data.drop(['Item_Type','Outlet_Establishment_Year'],axis=1,inplace=True)

In [35]:
#Divide into test and train:
train = data.loc[data['source']=="train"]
test = data.loc[data['source']=="test"]

In [36]:
#Drop unnecessary columns:
test.drop(['Item_Outlet_Sales','source'],axis=1,inplace=True)
train.drop(['source'],axis=1,inplace=True)

#Export files as modified versions:
train.to_csv("train_modified.csv",index=False)
test.to_csv("test_modified.csv",index=False)

/Applications/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Applications/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

# Model Building

In [37]:
# baseline Model

In [38]:
mean_sales = train['Item_Outlet_Sales'].mean()
mean_sales

2181.2889135750365

In [39]:
base1 = test[['Item_Identifier','Outlet_Identifier']]
base1['Item_Outlet_Sales'] = mean_sales

/Applications/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [40]:
#Export submission file
base1.to_csv('baseline.csv',index = False)

In [41]:
b = pd.read_csv('baseline.csv')

In [42]:
b.head()

  Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0           FDW58            OUT049        2181.288914
1           FDW14            OUT017        2181.288914
2           NCN55            OUT010        2181.288914
3           FDQ58            OUT017        2181.288914
4           FDY38            OUT027        2181.288914

a generic function which takes the algorithm and data as input and makes the model, performs 
cross-validation and generates submission.

In [43]:
#Define target and ID columns:
target = 'Item_Outlet_Sales'
IDcol = ['Item_Identifier','Outlet_Identifier']
from sklearn.model_selection import cross_val_score

def modelfit(alg, dtrain, dtest, predictors, target, IDcol, filename, resid=False, transform=False):
    #Fit the algorithm on the data
    alg.fit(dtrain[predictors], dtrain[target])
        
    #Predict training set:
    dtrain_predictions = alg.predict(dtrain[predictors])

    #Perform cross-validation:
    
    cv_score = cross_val_score(alg, dtrain[predictors], dtrain[target], cv=20, scoring='neg_mean_squared_error')
    cv_score = np.sqrt(np.abs(cv_score))
    
    #Print model report:
    print ("\nModel Report")
    print ("RMSE : %.4g" % np.sqrt(metrics.mean_squared_error(dtrain[target].values, dtrain_predictions)))
    print ("CV Score : Mean - %.4g | Std - %.4g | Min - %.4g | Max - %.4g" % (np.mean(cv_score),np.std(cv_score),np.min(cv_score),np.max(cv_score)))
    
    #Predict on testing data:
    dtest[target] = alg.predict(dtest[predictors])
    
    #Export submission file:
    IDcol.append(target)
    submission = pd.DataFrame({ x: dtest[x] for x in IDcol})
    submission.to_csv(filename, index=False)

In [44]:
# Linear Regression Model

In [45]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso

predictors = [x for x in train.columns if x not in [target]+IDcol]
# print predictors

alg1 = LinearRegression(normalize=True)
modelfit(alg1, train, test, predictors, target, IDcol, 'alg1.csv')
coef1 = pd.Series(alg1.coef_, predictors).sort_values()
coef1.plot(kind='bar', title='Model Coefficients',figsize=(10,6))

Model Report

NameError: name 'metrics' is not defined

In [ ]:
# Ridge Regression Model:

predictors = [x for x in train.columns if x not in [target]+IDcol]
alg2 = Ridge(alpha=0.05,normalize=True)
modelfit(alg2, train, test, predictors, target, IDcol, 'alg2.csv')
coef2 = pd.Series(alg2.coef_, predictors).sort_values()
coef2.plot(kind='bar', title='Model Coefficients',figsize=(10,6))

In [ ]:
# Decision Tree Model

from sklearn.tree import DecisionTreeRegressor
predictors = [x for x in train.columns if x not in [target]+IDcol]
alg3 = DecisionTreeRegressor(max_depth=15, min_samples_leaf=100)
modelfit(alg3, train, test, predictors, target, IDcol, 'alg3.csv')
coef3 = pd.Series(alg3.feature_importances_, predictors).sort_values(ascending=False)
coef3.plot(kind='bar', title='Feature Importances',figsize=(10,6))

In [ ]:
# Decision Tree with only 4 variables ,max depth of 8 and min samples of 50


predictors = ['Item_MRP','Outlet_Type_0','Outlet_5','Outlet_Years']
alg4 = DecisionTreeRegressor(max_depth=8, min_samples_leaf=150)
modelfit(alg4, train, test, predictors, target, IDcol, 'alg4.csv')
coef4 = pd.Series(alg4.feature_importances_, predictors).sort_values(ascending=False)
coef4.plot(kind='bar', title='Feature Importances')

In [ ]:
# random forest


from sklearn.ensemble import RandomForestRegressor
predictors = [x for x in train.columns if x not in [target]+IDcol]
alg5 = RandomForestRegressor(n_estimators=200,max_depth=5, min_samples_leaf=100,n_jobs=4)
modelfit(alg5, train, test, predictors, target, IDcol, 'alg5.csv')
coef5 = pd.Series(alg5.feature_importances_, predictors).sort_values(ascending=False)
coef5.plot(kind='bar', title='Feature Importances',figsize=(10,6))

In [ ]:
predictors = [x for x in train.columns if x not in [target]+IDcol]
alg6 = RandomForestRegressor(n_estimators=400,max_depth=6, min_samples_leaf=100,n_jobs=4)
modelfit(alg6, train, test, predictors, target, IDcol, 'alg6.csv')
coef6 = pd.Series(alg6.feature_importances_, predictors).sort_values(ascending=False)
coef6.plot(kind='bar', title='Feature Importances')